-- =====================================================================
-- RotaSorter seed — 010 reference data
-- Shifts, bench groups, the 20 benches and the competency documents
-- attached to each. Document numbers are the provisional register.
-- Synthetic data only. Generated by supabase/seed/generate_seed.py
-- =====================================================================

begin;

-- Wipe operational data first so this file can be re-run.
truncate table rule_breach, assignment, pin, rota_week, rota_run,
               staff_document, competency, availability, absence,
               bench_shift_requirement, competency_document,
               rule, solver_setting, staff, bench, bench_group, shift
         restart identity cascade;

-- Shifts ------------------------------------------------------------
insert into shift (code, name, starts_at, ends_at, is_default, sort_order) values
  ('DAY', 'Day', '08:30', '17:00', true, 0),
  ('LATE', 'Late', '17:00', '20:30', false, 1);

-- Bench groups ------------------------------------------------------
insert into bench_group (name, sort_order) values
  ('Urines', 0),
  ('Enteric', 1),
  ('Reading', 2),
  ('Sensitivities', 3),
  ('Processing', 4),
  ('Rapid & ID', 5),
  ('Containment', 6),
  ('Sterile Sites', 7),
  ('Molecular & Serology', 8),
  ('Reporting', 9);

-- Benches -----------------------------------------------------------
with data(name, group_name, min_staff, max_staff, required_level, sort_order) as (
  values
    ('Urines', 'Urines', 2, 3, 'competent', 0),
    ('Screening, Faeces and Tips Reading', 'Enteric', 1, 3, 'competent', 1),
    ('Faeces Microscopy', 'Enteric', 1, 2, 'competent', 2),
    ('Wounds Reading', 'Reading', 1, 2, 'competent', 3),
    ('Urogenitals Reading', 'Reading', 1, 2, 'competent', 4),
    ('ENT Reading', 'Reading', 1, 2, 'competent', 5),
    ('CAT-3 Reading', 'Reading', 1, 2, 'competent', 6),
    ('EUCAST Sensitivity Testing', 'Sensitivities', 1, 2, 'competent', 7),
    ('Processing Anaerobes', 'Processing', 1, 2, 'competent', 8),
    ('Deep Wounds/ Tissues', 'Processing', 1, 2, 'competent', 9),
    ('Trichomonas, Grams and Broths', 'Processing', 1, 2, 'competent', 10),
    ('Quick Tests', 'Rapid & ID', 1, 2, 'competent', 11),
    ('MALDI', 'Rapid & ID', 1, 2, 'competent', 12),
    ('CAT-3', 'Containment', 1, 2, 'competent', 13),
    ('Mycology', 'Containment', 1, 2, 'competent', 14),
    ('CSF', 'Sterile Sites', 1, 1, 'competent', 15),
    ('Blood Cultures', 'Sterile Sites', 1, 2, 'competent', 16),
    ('Molecular', 'Molecular & Serology', 1, 2, 'competent', 17),
    ('Serology', 'Molecular & Serology', 1, 2, 'competent', 18),
    ('Reporting Ref Lab Reports', 'Reporting', 1, 1, 'competent', 19)
)
insert into bench (name, group_id, min_staff, max_staff, required_level, sort_order)
select d.name, g.id, d.min_staff, d.max_staff, d.required_level::competency_level, d.sort_order
from data d
join bench_group g on g.name = d.group_name;

-- Competency documents ----------------------------------------------
with data(bench_name, doc_number, title, is_primary, sort_order) as (
  values
    ('Urines', '93', 'Urine culture: inoculation and plate reading', true, 0),
    ('Urines', '411', 'Urine microscopy and white cell counts', false, 1),
    ('Urines', '412', 'Urine antigen and dipstick screening', false, 2),
    ('Urines', '394', 'Urine specimen acceptance and rejection criteria', false, 3),
    ('Screening, Faeces and Tips Reading', '204', 'Faecal culture: primary plating', true, 0),
    ('Screening, Faeces and Tips Reading', '206', 'Rectal and wound screening swabs', false, 1),
    ('Screening, Faeces and Tips Reading', '395', 'Tips and line culture reading', false, 2),
    ('Screening, Faeces and Tips Reading', '414', 'Carbapenemase and MRSA screening plates', false, 3),
    ('Faeces Microscopy', '235', 'Faecal parasitology microscopy', true, 0),
    ('Wounds Reading', '396', 'Superficial wound plate reading', true, 0),
    ('Urogenitals Reading', '399', 'Urogenital plate reading and interpretation', true, 0),
    ('ENT Reading', '397', 'ENT and eye plate reading', true, 0),
    ('CAT-3 Reading', '398', 'Containment level 3 culture reading', true, 0),
    ('EUCAST Sensitivity Testing', '274', 'EUCAST disc diffusion sensitivity testing', true, 0),
    ('Processing Anaerobes', '205', 'Anaerobic culture set-up and incubation', true, 0),
    ('Processing Anaerobes', '134', 'Anaerobic identification and gas pack handling', false, 1),
    ('Deep Wounds/ Tissues', '401', 'Tissue and deep wound homogenisation', true, 0),
    ('Deep Wounds/ Tissues', '402', 'Deep wound culture set-up', false, 1),
    ('Deep Wounds/ Tissues', '403', 'Sonication of prosthetic material', false, 2),
    ('Deep Wounds/ Tissues', '404', 'Tissue culture reading and interpretation', false, 3),
    ('Deep Wounds/ Tissues', '407', 'Bone and joint sample handling', false, 4),
    ('Deep Wounds/ Tissues', '105', 'Sterile site specimen receipt', false, 5),
    ('Trichomonas, Grams and Broths', '241', 'Trichomonas wet preparation microscopy', true, 0),
    ('Trichomonas, Grams and Broths', '400', 'Gram film preparation and reporting', false, 1),
    ('Trichomonas, Grams and Broths', '111', 'Broth culture set-up and subculture', false, 2),
    ('Trichomonas, Grams and Broths', '406', 'Genital specimen processing', false, 3),
    ('Quick Tests', '132', 'Rapid antigen testing', true, 0),
    ('Quick Tests', '114', 'Latex agglutination tests', false, 1),
    ('Quick Tests', '112', 'Oxidase, catalase and coagulase', false, 2),
    ('Quick Tests', '133', 'Beta-lactamase detection', false, 3),
    ('Quick Tests', '98', 'Germ tube test', false, 4),
    ('Quick Tests', '142', 'Rapid urease testing', false, 5),
    ('Quick Tests', '438', 'Lateral flow toxin testing', false, 6),
    ('Quick Tests', '143', 'Indole and spot tests', false, 7),
    ('MALDI', '233', 'MALDI-TOF target preparation and identification', true, 0),
    ('CAT-3', '145', 'Containment level 3 entry, exit and PPE', true, 0),
    ('CAT-3', '323', 'Mycobacterial culture set-up', false, 1),
    ('CAT-3', '409', 'Auramine and ZN staining', false, 2),
    ('CAT-3', '410', 'Containment level 3 waste and spill handling', false, 3),
    ('CAT-3', '426', 'Mycobacterial molecular line probe assay', false, 4),
    ('CAT-3', '433', 'Containment level 3 safety cabinet operation', false, 5),
    ('Mycology', '339', 'Mycology culture, microscopy and identification', true, 0),
    ('CSF', '263', 'CSF microscopy and cell counts', true, 0),
    ('CSF', '265', 'CSF culture, antigen testing and reporting', false, 1),
    ('Blood Cultures', '266', 'Blood culture bottle handling and loading', true, 0),
    ('Blood Cultures', '267', 'Positive blood culture work-up and gram stain', false, 1),
    ('Molecular', '234', 'Molecular assay set-up and extraction', true, 0),
    ('Serology', '99', 'Serology sample preparation', true, 0),
    ('Serology', '135', 'Syphilis and treponemal serology', false, 1),
    ('Serology', '136', 'Serology analyser operation and QC', false, 2),
    ('Reporting Ref Lab Reports', '432', 'Reference laboratory report interpretation and filing', true, 0)
)
insert into competency_document (bench_id, doc_number, title, is_primary, sort_order)
select b.id, d.doc_number, d.title, d.is_primary, d.sort_order
from data d
join bench b on b.name = d.bench_name;

-- Which benches run on which days ------------------------------------
-- The Day shift only. See docs/ASSUMPTIONS.md for the Late shift.
with data(bench_name, label, weekdays, min_staff, max_staff) as (
  values
    ('Urines', 'standard', '{1,2,3,4,5}'::smallint[], 2, 3),
    ('Urines', 'weekend', '{6,7}'::smallint[], 1, 2),
    ('Screening, Faeces and Tips Reading', 'standard', '{1,2,3,4,5}'::smallint[], 1, 3),
    ('Faeces Microscopy', 'standard', '{1,3,5}'::smallint[], 1, 2),
    ('Wounds Reading', 'standard', '{1,2,3,4,5}'::smallint[], 1, 2),
    ('Urogenitals Reading', 'standard', '{2,4}'::smallint[], 1, 2),
    ('ENT Reading', 'standard', '{2,4}'::smallint[], 1, 2),
    ('CAT-3 Reading', 'standard', '{3,5}'::smallint[], 1, 2),
    ('EUCAST Sensitivity Testing', 'standard', '{1,2,3,4,5}'::smallint[], 1, 2),
    ('Processing Anaerobes', 'standard', '{1,3,5}'::smallint[], 1, 2),
    ('Deep Wounds/ Tissues', 'standard', '{1,2,3,4,5}'::smallint[], 1, 2),
    ('Trichomonas, Grams and Broths', 'standard', '{2,4}'::smallint[], 1, 2),
    ('Quick Tests', 'standard', '{1,2,3,4,5}'::smallint[], 1, 2),
    ('MALDI', 'standard', '{1,2,3,4,5}'::smallint[], 1, 2),
    ('CAT-3', 'standard', '{1,3}'::smallint[], 1, 2),
    ('Mycology', 'standard', '{4}'::smallint[], 1, 2),
    ('CSF', 'standard', '{1,2,3,4,5}'::smallint[], 1, 1),
    ('Blood Cultures', 'standard', '{1,2,3,4,5}'::smallint[], 1, 2),
    ('Blood Cultures', 'weekend', '{6,7}'::smallint[], 1, 1),
    ('Molecular', 'standard', '{3}'::smallint[], 1, 2),
    ('Serology', 'standard', '{4}'::smallint[], 1, 2),
    ('Reporting Ref Lab Reports', 'standard', '{3}'::smallint[], 1, 1)
)
insert into bench_shift_requirement (bench_id, shift_id, label, weekdays,
                                     min_staff, max_staff)
select b.id, s.id, d.label, d.weekdays, d.min_staff, d.max_staff
from data d
join bench b on b.name = d.bench_name
join shift s on s.code = 'DAY';

commit;
