-- =====================================================================
-- RotaSorter seed — 020 staff, patterns and absences
-- 20 synthetic staff across four grades, with contracted patterns that
-- leave 1-3 people of headroom on a weekday and three on a weekend.
-- Synthetic data only. Generated by supabase/seed/generate_seed.py
-- =====================================================================

begin;

-- Staff --------------------------------------------------------------
insert into staff (staff_code, full_name, grade, fte, started_on, status) values
  ('SBMS-0041', 'Alison Ferreira', 'senior_bms', 1.00, '2011-04-04', 'active'),
  ('SBMS-0058', 'Rakesh Menon', 'senior_bms', 1.00, '2013-09-02', 'active'),
  ('SBMS-0063', 'Claire Dunwoody', 'senior_bms', 1.00, '2014-01-13', 'active'),
  ('BMS-0112', 'Priya Raman', 'bms', 1.00, '2017-06-05', 'active'),
  ('BMS-0127', 'Tom Whitfield', 'bms', 1.00, '2018-02-19', 'active'),
  ('BMS-0134', 'Grace Okonkwo', 'bms', 1.00, '2018-10-01', 'active'),
  ('BMS-0141', 'Marcus Kell', 'bms', 1.00, '2019-03-25', 'active'),
  ('BMS-0155', 'Sarah Patel', 'bms', 1.00, '2019-11-04', 'active'),
  ('BMS-0168', 'Daniel Achebe', 'bms', 0.80, '2020-07-06', 'active'),
  ('BMS-0173', 'Nadia Hussain', 'bms', 0.80, '2021-01-11', 'active'),
  ('BMS-0189', 'Owen Brackley', 'bms', 1.00, '2021-09-13', 'active'),
  ('BMS-0194', 'Lucy Tran', 'bms', 1.00, '2022-04-19', 'active'),
  ('BMS-0201', 'Ibrahim Sesay', 'bms', 1.00, '2022-08-30', 'active'),
  ('AP-0303', 'Dawn Rutherford', 'ap', 1.00, '2015-05-18', 'active'),
  ('AP-0311', 'Kyle Mbeki', 'ap', 0.60, '2020-02-03', 'active'),
  ('AP-0318', 'Fiona Castellano', 'ap', 1.00, '2021-06-14', 'active'),
  ('AP-0326', 'Reece Underhill', 'ap', 1.00, '2023-01-09', 'active'),
  ('TRN-0402', 'Hannah Ng', 'trainee', 1.00, '2025-09-01', 'active'),
  ('TRN-0409', 'Josef Kaminski', 'trainee', 1.00, '2026-01-12', 'active'),
  ('TRN-0415', 'Amara Diallo', 'trainee', 1.00, '2026-04-20', 'active');

-- Contracted patterns (Day shift) ------------------------------------
-- weekday is ISO: 1 = Monday .. 7 = Sunday. A row exists only for the
-- days a person is contracted to work.
with data(staff_code, weekday) as (
  values
    ('SBMS-0041', 1::smallint),
    ('SBMS-0041', 2::smallint),
    ('SBMS-0041', 3::smallint),
    ('SBMS-0041', 4::smallint),
    ('SBMS-0041', 5::smallint),
    ('SBMS-0058', 1::smallint),
    ('SBMS-0058', 2::smallint),
    ('SBMS-0058', 3::smallint),
    ('SBMS-0058', 4::smallint),
    ('SBMS-0058', 5::smallint),
    ('SBMS-0063', 1::smallint),
    ('SBMS-0063', 2::smallint),
    ('SBMS-0063', 3::smallint),
    ('SBMS-0063', 4::smallint),
    ('SBMS-0063', 5::smallint),
    ('BMS-0112', 1::smallint),
    ('BMS-0112', 2::smallint),
    ('BMS-0112', 3::smallint),
    ('BMS-0112', 4::smallint),
    ('BMS-0112', 5::smallint),
    ('BMS-0127', 1::smallint),
    ('BMS-0127', 2::smallint),
    ('BMS-0127', 3::smallint),
    ('BMS-0127', 4::smallint),
    ('BMS-0127', 5::smallint),
    ('BMS-0134', 1::smallint),
    ('BMS-0134', 2::smallint),
    ('BMS-0134', 3::smallint),
    ('BMS-0134', 4::smallint),
    ('BMS-0134', 5::smallint),
    ('BMS-0141', 1::smallint),
    ('BMS-0141', 2::smallint),
    ('BMS-0141', 3::smallint),
    ('BMS-0141', 4::smallint),
    ('BMS-0141', 5::smallint),
    ('BMS-0155', 1::smallint),
    ('BMS-0155', 2::smallint),
    ('BMS-0155', 3::smallint),
    ('BMS-0155', 4::smallint),
    ('BMS-0155', 5::smallint),
    ('BMS-0168', 1::smallint),
    ('BMS-0168', 2::smallint),
    ('BMS-0168', 3::smallint),
    ('BMS-0168', 4::smallint),
    ('BMS-0173', 2::smallint),
    ('BMS-0173', 3::smallint),
    ('BMS-0173', 4::smallint),
    ('BMS-0173', 5::smallint),
    ('BMS-0189', 1::smallint),
    ('BMS-0189', 2::smallint),
    ('BMS-0189', 3::smallint),
    ('BMS-0189', 4::smallint),
    ('BMS-0189', 5::smallint),
    ('BMS-0194', 3::smallint),
    ('BMS-0194', 4::smallint),
    ('BMS-0194', 5::smallint),
    ('BMS-0194', 6::smallint),
    ('BMS-0194', 7::smallint),
    ('BMS-0201', 3::smallint),
    ('BMS-0201', 4::smallint),
    ('BMS-0201', 5::smallint),
    ('BMS-0201', 6::smallint),
    ('BMS-0201', 7::smallint),
    ('AP-0303', 1::smallint),
    ('AP-0303', 2::smallint),
    ('AP-0303', 3::smallint),
    ('AP-0303', 4::smallint),
    ('AP-0303', 5::smallint),
    ('AP-0311', 1::smallint),
    ('AP-0311', 2::smallint),
    ('AP-0311', 3::smallint),
    ('AP-0318', 3::smallint),
    ('AP-0318', 4::smallint),
    ('AP-0318', 5::smallint),
    ('AP-0318', 6::smallint),
    ('AP-0318', 7::smallint),
    ('AP-0326', 1::smallint),
    ('AP-0326', 2::smallint),
    ('AP-0326', 3::smallint),
    ('AP-0326', 4::smallint),
    ('AP-0326', 5::smallint),
    ('TRN-0402', 1::smallint),
    ('TRN-0402', 2::smallint),
    ('TRN-0402', 3::smallint),
    ('TRN-0402', 4::smallint),
    ('TRN-0402', 5::smallint),
    ('TRN-0409', 1::smallint),
    ('TRN-0409', 2::smallint),
    ('TRN-0409', 3::smallint),
    ('TRN-0409', 4::smallint),
    ('TRN-0409', 5::smallint),
    ('TRN-0415', 1::smallint),
    ('TRN-0415', 2::smallint),
    ('TRN-0415', 3::smallint),
    ('TRN-0415', 4::smallint),
    ('TRN-0415', 5::smallint)
)
insert into availability (staff_id, weekday, shift_id, is_available)
select s.id, d.weekday, sh.id, true
from data d
join staff s on s.staff_code = d.staff_code
join shift sh on sh.code = 'DAY';

-- Absences -----------------------------------------------------------
with data(staff_code, starts_on, ends_on, kind, notes) as (
  values
    ('BMS-0112', '2026-09-14', '2026-09-16', 'annual_leave', 'Booked April'),
    ('BMS-0127', '2026-09-17', '2026-09-18', 'annual_leave', null),
    ('BMS-0134', '2026-09-15', '2026-09-15', 'sick', 'Called in 07:10'),
    ('BMS-0141', '2026-09-28', '2026-10-02', 'annual_leave', null),
    ('TRN-0402', '2026-09-23', '2026-09-23', 'study', 'University day'),
    ('AP-0303', '2026-09-21', '2026-09-25', 'annual_leave', null),
    ('BMS-0201', '2026-09-07', '2026-09-11', 'annual_leave', null),
    ('AP-0326', '2026-08-24', '2026-08-28', 'annual_leave', null)
)
insert into absence (staff_id, starts_on, ends_on, kind, notes)
select s.id, d.starts_on, d.ends_on, d.kind::absence_kind, d.notes
from data d
join staff s on s.staff_code = d.staff_code;

commit;
