-- =====================================================================
-- RotaSorter seed — 040 rules and solver settings
-- Seven active rules plus one paused rule you can switch on to see the
-- infeasibility explanation do its job.
-- Synthetic data only. Generated by supabase/seed/generate_seed.py
-- =====================================================================

begin;

-- Rules --------------------------------------------------------------
-- Condition values reference staff by staff_code and benches by name;
-- the solver resolves them at load time.
insert into rule (name, description, action, params, conditions, scope, is_hard, weight, status, plain_english) values
  (
    'CAT-3 needs a trainer on the bench',
    'Containment level 3 work is never done unsupervised.',
    'requires_supervisor',
    '{"supervisor_level": "trainer"}'::jsonb,
    '{"op": "all", "children": [{"subject": "bench", "operator": "is", "values": ["CAT-3"]}]}'::jsonb,
    'bench',
    true,
    100,
    'active',
    'Any day CAT-3 is staffed, at least one person on it must be a trainer.'
  ),
  (
    'Reference lab reports need a Senior BMS',
    'Only a senior signs off reference laboratory report interpretation.',
    'requires_at_least',
    '{"n": 1}'::jsonb,
    '{"op": "all", "children": [{"subject": "bench", "operator": "is", "values": ["Reporting Ref Lab Reports"]}, {"subject": "grade", "operator": "is", "values": ["senior_bms"]}]}'::jsonb,
    'bench',
    true,
    100,
    'active',
    'Reporting Ref Lab Reports must have at least 1 Senior BMS on it.'
  ),
  (
    'Keep Marcus Kell and Sarah Patel apart',
    'Requested by both. Do not put them on the same bench.',
    'not_together',
    '{}'::jsonb,
    '{"op": "all", "children": [{"subject": "person", "operator": "is one of", "values": ["BMS-0141", "BMS-0155"]}]}'::jsonb,
    'staff',
    true,
    100,
    'active',
    'Marcus Kell and Sarah Patel are never on the same bench on the same day.'
  ),
  (
    'No trainees on CSF',
    'CSF is urgent and low volume; training happens elsewhere.',
    'cannot_be_assigned',
    '{}'::jsonb,
    '{"op": "all", "children": [{"subject": "grade", "operator": "is", "values": ["trainee"]}, {"subject": "bench", "operator": "is", "values": ["CSF"]}]}'::jsonb,
    'bench',
    true,
    100,
    'active',
    'Anyone at Trainee grade cannot be assigned to CSF.'
  ),
  (
    'Hannah Ng holds one bench all week',
    'Training block. Continuity matters more than variety while she signs off.',
    'same_bench_all_week',
    '{}'::jsonb,
    '{"op": "all", "children": [{"subject": "person", "operator": "is", "values": ["TRN-0402"]}]}'::jsonb,
    'staff',
    false,
    70,
    'active',
    'Hannah Ng should stay on the same bench every day this week.'
  ),
  (
    'Cap Urines at three days a week',
    'Urines is the heaviest bench. Spread it.',
    'max_shifts_in_period',
    '{"n": 3}'::jsonb,
    '{"op": "all", "children": [{"subject": "bench", "operator": "is", "values": ["Urines"]}]}'::jsonb,
    'bench',
    false,
    40,
    'active',
    'Nobody should be on Urines more than 3 days in the week.'
  ),
  (
    'At most one trainee on Urines',
    'One trainee at a time so the signed-off staff can actually supervise.',
    'requires_at_most',
    '{"n": 1}'::jsonb,
    '{"op": "all", "children": [{"subject": "bench", "operator": "is", "values": ["Urines"]}, {"subject": "grade", "operator": "is", "values": ["trainee"]}]}'::jsonb,
    'bench',
    false,
    50,
    'active',
    'Urines should have at most 1 person at Trainee grade on it.'
  ),
  (
    'Blood Cultures needs three people',
    'Paused. Turn this on to demonstrate the infeasibility explanation.',
    'requires_at_least',
    '{"n": 3}'::jsonb,
    '{"op": "all", "children": [{"subject": "bench", "operator": "is", "values": ["Blood Cultures"]}]}'::jsonb,
    'bench',
    true,
    100,
    'paused',
    'Blood Cultures must have at least 3 people on it.'
  );

-- Solver settings ----------------------------------------------------
insert into solver_setting (key, value, label, description, sort_order) values
  ('weight_fairness_spread', '20'::jsonb, 'Fairness', 'Cost per repeat of the gap between the most and least repeated person.', 0),
  ('weight_rotation_repeat', '12'::jsonb, 'Rotation', 'Cost each time someone repeats a bench they were already on this week.', 1),
  ('weight_idle_staff', '40'::jsonb, 'Idle staff', 'Cost of leaving an available member of staff off the rota for a day.', 2),
  ('weight_trainee_placement', '25'::jsonb, 'Trainee placement', 'Extra cost of leaving a trainee off the rota, on top of the idle cost.', 3),
  ('weight_soft_breach_scale', '1'::jsonb, 'Soft rule scale', 'Multiplier applied to each soft rule''s own weight.', 4),
  ('max_solve_seconds', '60'::jsonb, 'Solve time limit', 'Seconds the CP-SAT solver may spend before returning its best answer.', 5),
  ('random_seed', '20260914'::jsonb, 'Random seed', 'Fixed so the same inputs give the same rota.', 6),
  ('history_from_unpublished', '0'::jsonb, 'Plan against unpublished weeks', 'When last week has no published rota, count its latest solved run instead. Runs planned this way cannot be published until that week is.', 100),
  ('allow_publish_out_of_order', '0'::jsonb, 'Allow out-of-order publishing', 'Publish a week even though the rota it was planned against has not been published. The runs it counted may no longer be what that week gets.', 101);

commit;
