-- =====================================================================
-- RotaSorter seed — 050 weekday cover expansion
-- Additive: makes every bench run every weekday and adds the ten staff
-- that requires. Safe to run on a database already seeded from
-- 0010-0040, where it does nothing. Not needed for a fresh install.
-- Synthetic data only. Generated by supabase/seed/generate_seed.py
-- =====================================================================

begin;

-- Every bench runs every weekday ------------------------------------
-- Benches used to run on the two or three days their work arrived, so
-- the Rota Board read "Not run" for most of the grid. The weekend rows
-- are left alone: Saturday and Sunday stay Urines and Blood Cultures,
-- one person each.
update bench_shift_requirement r
   set weekdays = '{1,2,3,4,5}'::smallint[]
  from shift s
 where s.id = r.shift_id
   and s.code = 'DAY'
   and r.label = 'standard'
   and r.weekdays <> '{1,2,3,4,5}'::smallint[];

-- The ten new staff ---------------------------------------------------
-- Synthetic, like everyone else here. Two Senior BMS so reference lab
-- reports and CAT-3 are not one person deep, five BMS and three APs.
insert into staff (staff_code, full_name, grade, fte, started_on, status) values
  ('SBMS-0071', 'Meredith Vance', 'senior_bms', 1.00, '2016-02-15', 'active'),
  ('SBMS-0084', 'Anil Bhattacharya', 'senior_bms', 1.00, '2017-10-02', 'active'),
  ('BMS-0212', 'Erin Kowalczyk', 'bms', 1.00, '2020-03-16', 'active'),
  ('BMS-0223', 'Femi Adeyemi', 'bms', 1.00, '2021-05-10', 'active'),
  ('BMS-0237', 'Ruth Sandiford', 'bms', 1.00, '2019-08-19', 'active'),
  ('BMS-0245', 'Callum Reith', 'bms', 1.00, '2022-11-07', 'active'),
  ('BMS-0258', 'Harriet Loxley', 'bms', 1.00, '2023-04-03', 'active'),
  ('AP-0334', 'Bea Nakamura', 'ap', 1.00, '2021-09-27', 'active'),
  ('AP-0341', 'Stefan Oyelaran', 'ap', 0.80, '2023-02-13', 'active'),
  ('AP-0349', 'Marta Kubiak', 'ap', 0.60, '2024-07-15', 'active')
on conflict (staff_code) do nothing;

-- Their contracted patterns (Day shift) -------------------------------
with data(staff_code, weekday) as (
  values
    ('SBMS-0071', 1::smallint),
    ('SBMS-0071', 2::smallint),
    ('SBMS-0071', 3::smallint),
    ('SBMS-0071', 4::smallint),
    ('SBMS-0071', 5::smallint),
    ('SBMS-0084', 1::smallint),
    ('SBMS-0084', 2::smallint),
    ('SBMS-0084', 3::smallint),
    ('SBMS-0084', 4::smallint),
    ('SBMS-0084', 5::smallint),
    ('BMS-0212', 1::smallint),
    ('BMS-0212', 2::smallint),
    ('BMS-0212', 3::smallint),
    ('BMS-0212', 4::smallint),
    ('BMS-0212', 5::smallint),
    ('BMS-0223', 1::smallint),
    ('BMS-0223', 2::smallint),
    ('BMS-0223', 3::smallint),
    ('BMS-0223', 4::smallint),
    ('BMS-0223', 5::smallint),
    ('BMS-0237', 1::smallint),
    ('BMS-0237', 2::smallint),
    ('BMS-0237', 3::smallint),
    ('BMS-0237', 4::smallint),
    ('BMS-0237', 5::smallint),
    ('BMS-0245', 1::smallint),
    ('BMS-0245', 2::smallint),
    ('BMS-0245', 3::smallint),
    ('BMS-0245', 4::smallint),
    ('BMS-0245', 5::smallint),
    ('BMS-0258', 1::smallint),
    ('BMS-0258', 2::smallint),
    ('BMS-0258', 3::smallint),
    ('BMS-0258', 4::smallint),
    ('BMS-0258', 5::smallint),
    ('AP-0334', 1::smallint),
    ('AP-0334', 2::smallint),
    ('AP-0334', 3::smallint),
    ('AP-0334', 4::smallint),
    ('AP-0334', 5::smallint),
    ('AP-0341', 1::smallint),
    ('AP-0341', 2::smallint),
    ('AP-0341', 3::smallint),
    ('AP-0341', 4::smallint),
    ('AP-0349', 1::smallint),
    ('AP-0349', 2::smallint),
    ('AP-0349', 3::smallint)
)
insert into availability (staff_id, weekday, shift_id, is_available)
select s.id, d.weekday, sh.id, true
from data d
join staff s on s.staff_code = d.staff_code
join shift sh on sh.code = 'DAY'
on conflict (staff_id, weekday, shift_id) do nothing;

-- What they are signed off on ----------------------------------------
with data(staff_code, bench_name, level, assessed_on, expires_on, assessor_code) as (
  values
    ('SBMS-0071', 'Urines', 'competent', '2024-08-27', '2027-08-27', 'SBMS-0058'),
    ('SBMS-0084', 'Urines', 'competent', '2024-12-10', '2027-12-10', 'SBMS-0041'),
    ('BMS-0212', 'Urines', 'competent', '2025-03-12', '2028-03-11', 'SBMS-0058'),
    ('BMS-0223', 'Urines', 'competent', '2025-06-23', '2028-06-22', 'AP-0303'),
    ('BMS-0237', 'Urines', 'competent', '2026-05-21', '2029-05-20', 'SBMS-0041'),
    ('BMS-0245', 'Urines', 'competent', '2024-05-29', '2027-05-29', 'AP-0303'),
    ('BMS-0258', 'Urines', 'competent', '2025-01-30', '2028-01-30', 'AP-0303'),
    ('AP-0334', 'Urines', 'competent', '2024-12-07', '2027-12-07', 'SBMS-0063'),
    ('AP-0341', 'Urines', 'competent', '2024-04-25', '2027-04-25', 'SBMS-0063'),
    ('AP-0349', 'Urines', 'competent', '2026-01-21', '2029-01-20', 'SBMS-0041'),
    ('SBMS-0071', 'Screening, Faeces and Tips Reading', 'competent', '2025-06-13', '2028-06-12', 'AP-0303'),
    ('SBMS-0084', 'Screening, Faeces and Tips Reading', 'competent', '2026-04-17', '2029-04-16', 'SBMS-0063'),
    ('BMS-0212', 'Screening, Faeces and Tips Reading', 'competent', '2025-09-12', '2028-09-11', 'AP-0303'),
    ('BMS-0223', 'Screening, Faeces and Tips Reading', 'competent', '2024-06-26', '2027-06-26', 'SBMS-0058'),
    ('BMS-0237', 'Screening, Faeces and Tips Reading', 'competent', '2024-06-20', '2027-06-20', 'AP-0303'),
    ('BMS-0245', 'Screening, Faeces and Tips Reading', 'competent', '2025-09-10', '2028-09-09', 'SBMS-0063'),
    ('BMS-0258', 'Screening, Faeces and Tips Reading', 'competent', '2024-06-15', '2027-06-15', 'SBMS-0063'),
    ('AP-0334', 'Screening, Faeces and Tips Reading', 'competent', '2024-03-15', '2027-03-15', 'SBMS-0041'),
    ('AP-0341', 'Screening, Faeces and Tips Reading', 'competent', '2024-06-01', '2027-06-01', 'AP-0303'),
    ('AP-0349', 'Screening, Faeces and Tips Reading', 'competent', '2025-11-28', '2028-11-27', 'SBMS-0041'),
    ('BMS-0223', 'Faeces Microscopy', 'competent', '2025-04-03', '2028-04-02', 'SBMS-0041'),
    ('BMS-0258', 'Faeces Microscopy', 'competent', '2025-03-06', '2028-03-05', 'SBMS-0058'),
    ('AP-0334', 'Faeces Microscopy', 'competent', '2024-05-12', '2027-05-12', 'SBMS-0041'),
    ('AP-0349', 'Faeces Microscopy', 'competent', '2025-03-23', '2028-03-22', 'SBMS-0063'),
    ('SBMS-0071', 'Wounds Reading', 'competent', '2024-11-25', '2027-11-25', 'SBMS-0058'),
    ('BMS-0212', 'Wounds Reading', 'competent', '2024-08-15', '2027-08-15', 'AP-0303'),
    ('BMS-0223', 'Wounds Reading', 'competent', '2024-06-21', '2027-06-21', 'AP-0303'),
    ('BMS-0237', 'Wounds Reading', 'competent', '2025-05-07', '2028-05-06', 'SBMS-0041'),
    ('BMS-0258', 'Wounds Reading', 'competent', '2025-01-08', '2028-01-08', 'SBMS-0058'),
    ('AP-0341', 'Wounds Reading', 'competent', '2026-05-19', '2029-05-18', 'AP-0303'),
    ('BMS-0223', 'Urogenitals Reading', 'competent', '2026-05-11', '2029-05-10', 'SBMS-0063'),
    ('BMS-0237', 'Urogenitals Reading', 'competent', '2024-07-19', '2027-07-19', 'SBMS-0058'),
    ('BMS-0258', 'Urogenitals Reading', 'competent', '2024-07-27', '2027-07-27', 'SBMS-0063'),
    ('BMS-0212', 'ENT Reading', 'competent', '2025-06-09', '2028-06-08', 'SBMS-0041'),
    ('BMS-0223', 'ENT Reading', 'competent', '2025-05-09', '2028-05-08', 'AP-0303'),
    ('BMS-0258', 'ENT Reading', 'competent', '2024-11-06', '2027-11-06', 'SBMS-0058'),
    ('SBMS-0071', 'CAT-3 Reading', 'competent', '2025-04-14', '2028-04-13', 'SBMS-0063'),
    ('SBMS-0084', 'CAT-3 Reading', 'trainer', '2024-12-21', '2027-12-21', 'SBMS-0058'),
    ('BMS-0223', 'CAT-3 Reading', 'competent', '2026-04-03', '2029-04-02', 'SBMS-0058'),
    ('BMS-0245', 'CAT-3 Reading', 'competent', '2025-07-05', '2028-07-04', 'SBMS-0063'),
    ('SBMS-0071', 'EUCAST Sensitivity Testing', 'competent', '2026-06-17', '2029-06-16', 'AP-0303'),
    ('SBMS-0084', 'EUCAST Sensitivity Testing', 'competent', '2026-02-04', '2029-02-03', 'SBMS-0063'),
    ('BMS-0212', 'EUCAST Sensitivity Testing', 'competent', '2024-11-29', '2027-11-29', 'SBMS-0041'),
    ('BMS-0237', 'EUCAST Sensitivity Testing', 'competent', '2025-10-17', '2028-10-16', 'SBMS-0058'),
    ('BMS-0245', 'EUCAST Sensitivity Testing', 'competent', '2026-03-09', '2029-03-08', 'SBMS-0063'),
    ('BMS-0258', 'EUCAST Sensitivity Testing', 'competent', '2024-03-05', '2027-03-05', 'SBMS-0058'),
    ('AP-0341', 'EUCAST Sensitivity Testing', 'competent', '2025-05-07', '2028-05-06', 'SBMS-0058'),
    ('BMS-0245', 'Processing Anaerobes', 'competent', '2025-06-04', '2028-06-03', 'SBMS-0058'),
    ('BMS-0258', 'Processing Anaerobes', 'competent', '2025-07-24', '2028-07-23', 'SBMS-0041'),
    ('AP-0334', 'Processing Anaerobes', 'competent', '2026-04-09', '2029-04-08', 'SBMS-0041'),
    ('AP-0341', 'Processing Anaerobes', 'competent', '2024-05-08', '2027-05-08', 'SBMS-0041'),
    ('SBMS-0071', 'Deep Wounds/ Tissues', 'competent', '2026-06-20', '2029-06-19', 'SBMS-0063'),
    ('SBMS-0084', 'Deep Wounds/ Tissues', 'competent', '2026-02-24', '2029-02-23', 'SBMS-0058'),
    ('BMS-0237', 'Deep Wounds/ Tissues', 'competent', '2024-08-26', '2027-08-26', 'SBMS-0041'),
    ('BMS-0245', 'Deep Wounds/ Tissues', 'competent', '2024-12-08', '2027-12-08', 'AP-0303'),
    ('BMS-0258', 'Deep Wounds/ Tissues', 'competent', '2024-08-08', '2027-08-08', 'AP-0303'),
    ('BMS-0237', 'Trichomonas, Grams and Broths', 'competent', '2025-03-01', '2028-02-29', 'SBMS-0063'),
    ('BMS-0258', 'Trichomonas, Grams and Broths', 'competent', '2025-06-22', '2028-06-21', 'AP-0303'),
    ('AP-0334', 'Trichomonas, Grams and Broths', 'competent', '2024-11-23', '2027-11-23', 'AP-0303'),
    ('AP-0349', 'Trichomonas, Grams and Broths', 'competent', '2025-12-28', '2028-12-27', 'SBMS-0058'),
    ('SBMS-0071', 'Quick Tests', 'competent', '2026-01-20', '2029-01-19', 'SBMS-0063'),
    ('SBMS-0084', 'Quick Tests', 'competent', '2026-03-26', '2029-03-25', 'SBMS-0063'),
    ('BMS-0212', 'Quick Tests', 'competent', '2025-10-10', '2028-10-09', 'SBMS-0041'),
    ('BMS-0223', 'Quick Tests', 'competent', '2025-06-02', '2028-06-01', 'AP-0303'),
    ('BMS-0237', 'Quick Tests', 'competent', '2026-02-13', '2029-02-12', 'SBMS-0041'),
    ('BMS-0245', 'Quick Tests', 'competent', '2024-04-12', '2027-04-12', 'AP-0303'),
    ('BMS-0258', 'Quick Tests', 'competent', '2024-11-17', '2027-11-17', 'SBMS-0058'),
    ('AP-0334', 'Quick Tests', 'competent', '2025-06-11', '2028-06-10', 'SBMS-0058'),
    ('AP-0341', 'Quick Tests', 'competent', '2024-04-27', '2027-04-27', 'SBMS-0058'),
    ('AP-0349', 'Quick Tests', 'competent', '2026-04-29', '2029-04-28', 'SBMS-0063'),
    ('SBMS-0071', 'MALDI', 'competent', '2024-06-02', '2027-06-02', 'SBMS-0058'),
    ('SBMS-0084', 'MALDI', 'competent', '2024-03-17', '2027-03-17', 'AP-0303'),
    ('BMS-0212', 'MALDI', 'competent', '2025-07-11', '2028-07-10', 'SBMS-0041'),
    ('BMS-0223', 'MALDI', 'competent', '2025-07-05', '2028-07-04', 'AP-0303'),
    ('BMS-0237', 'MALDI', 'competent', '2024-10-20', '2027-10-20', 'SBMS-0063'),
    ('BMS-0245', 'MALDI', 'competent', '2026-02-15', '2029-02-14', 'SBMS-0063'),
    ('AP-0334', 'MALDI', 'competent', '2026-01-16', '2029-01-15', 'SBMS-0063'),
    ('AP-0341', 'MALDI', 'competent', '2026-01-18', '2029-01-17', 'SBMS-0058'),
    ('SBMS-0071', 'CAT-3', 'competent', '2026-04-08', '2029-04-07', 'SBMS-0058'),
    ('SBMS-0084', 'CAT-3', 'trainer', '2026-02-05', '2029-02-04', 'SBMS-0063'),
    ('BMS-0245', 'CAT-3', 'competent', '2025-08-15', '2028-08-14', 'SBMS-0041'),
    ('SBMS-0084', 'Mycology', 'trainer', '2025-08-06', '2028-08-05', 'SBMS-0058'),
    ('BMS-0212', 'Mycology', 'competent', '2024-04-13', '2027-04-13', 'SBMS-0041'),
    ('BMS-0245', 'Mycology', 'competent', '2024-03-01', '2027-03-01', 'SBMS-0063'),
    ('SBMS-0071', 'CSF', 'competent', '2024-09-04', '2027-09-04', 'SBMS-0041'),
    ('BMS-0212', 'CSF', 'competent', '2025-02-10', '2028-02-10', 'SBMS-0063'),
    ('BMS-0237', 'CSF', 'competent', '2026-04-14', '2029-04-13', 'SBMS-0063'),
    ('SBMS-0071', 'Blood Cultures', 'competent', '2026-05-19', '2029-05-18', 'SBMS-0041'),
    ('SBMS-0084', 'Blood Cultures', 'competent', '2025-05-06', '2028-05-05', 'SBMS-0058'),
    ('BMS-0212', 'Blood Cultures', 'competent', '2024-04-24', '2027-04-24', 'AP-0303'),
    ('BMS-0237', 'Blood Cultures', 'competent', '2024-04-26', '2027-04-26', 'SBMS-0063'),
    ('BMS-0245', 'Blood Cultures', 'competent', '2026-01-24', '2029-01-23', 'SBMS-0058'),
    ('BMS-0258', 'Blood Cultures', 'competent', '2024-09-19', '2027-09-19', 'AP-0303'),
    ('SBMS-0071', 'Molecular', 'trainer', '2024-08-12', '2027-08-12', 'SBMS-0041'),
    ('SBMS-0084', 'Molecular', 'competent', '2025-10-30', '2028-10-29', 'AP-0303'),
    ('BMS-0212', 'Molecular', 'competent', '2024-12-10', '2027-12-10', 'SBMS-0063'),
    ('SBMS-0071', 'Serology', 'trainer', '2024-07-27', '2027-07-27', 'SBMS-0063'),
    ('BMS-0212', 'Serology', 'competent', '2024-11-09', '2027-11-09', 'SBMS-0063'),
    ('BMS-0237', 'Serology', 'competent', '2024-04-28', '2027-04-28', 'SBMS-0041'),
    ('SBMS-0071', 'Reporting Ref Lab Reports', 'trainer', '2024-06-04', '2027-06-04', 'SBMS-0041'),
    ('SBMS-0084', 'Reporting Ref Lab Reports', 'competent', '2024-09-24', '2027-09-24', 'AP-0303')
)
insert into competency (staff_id, bench_id, level, assessed_on, expires_on,
                        assessor_id, document_ref)
select
  s.id,
  b.id,
  d.level::competency_level,
  d.assessed_on::date,
  d.expires_on::date,
  a.id,
  (select cd.doc_number
     from competency_document cd
    where cd.bench_id = b.id
    order by cd.sort_order
    limit 1)
from data d
join staff s on s.staff_code = d.staff_code
join bench b on b.name = d.bench_name
left join staff a on a.staff_code = d.assessor_code
on conflict (staff_id, bench_id) do nothing;

-- Evidence trail: signed-off staff hold every document for the bench.
insert into staff_document (staff_id, document_id, status, assessed_on, expires_on)
select c.staff_id, cd.id, 'signed_off', c.assessed_on, c.expires_on
from competency c
join staff s on s.id = c.staff_id
join competency_document cd on cd.bench_id = c.bench_id
where c.level in ('competent', 'trainer')
  and s.staff_code in ('SBMS-0071', 'SBMS-0084', 'BMS-0212', 'BMS-0223', 'BMS-0237', 'BMS-0245', 'BMS-0258', 'AP-0334', 'AP-0341', 'AP-0349')
on conflict (staff_id, document_id) do nothing;

commit;

-- Did it work? One row per weekday: how many people the benches ask for
-- that day, and how many signed-off staff are contracted to be in. The
-- second number has to be at least the first, and a couple higher is
-- what keeps the week solvable when somebody rings in sick.
select
  d.weekday,
  (select coalesce(sum(r.min_staff), 0)
     from bench_shift_requirement r
     join shift sh on sh.id = r.shift_id and sh.code = 'DAY'
    where d.weekday = any (r.weekdays))                    as people_needed,
  (select count(*)
     from staff s
    where s.status = 'active'
      and exists (select 1
                    from availability a
                    join shift sh on sh.id = a.shift_id and sh.code = 'DAY'
                   where a.staff_id = s.id
                     and a.weekday = d.weekday
                     and a.is_available)
      and exists (select 1
                    from competency c
                   where c.staff_id = s.id
                     and c.level in ('competent', 'trainer')
                     and (c.expires_on is null
                          or c.expires_on >= current_date)))  as signed_off_in
from generate_series(1, 7) as d(weekday)
order by d.weekday;
