#!/usr/bin/env python3
"""Generate the RotaSorter synthetic seed SQL.

Everything here is invented. No real employee records at any point.

    python3 supabase/seed/generate_seed.py

Writes the numbered .sql files next to this script. Run them in the Supabase
SQL editor after the three migrations.

The roster is deliberately tuned so the seeded week solves but is not roomy:
weekday headroom is 1-3 people. That is what makes the Rota Board worth
looking at. `python3 -m rotasolver.cli --self-check` in solver/ re-verifies it.
"""

from __future__ import annotations

import random
import textwrap
from datetime import date, timedelta
from pathlib import Path

OUT = Path(__file__).parent
SEED_WEEK = date(2026, 9, 14)          # Monday, the week the spec mocks up
TODAY = date(2026, 8, 19)              # reference point for expiry states
RNG = random.Random(20260914)

MON, TUE, WED, THU, FRI, SAT, SUN = 1, 2, 3, 4, 5, 6, 7
WEEKDAYS = [MON, TUE, WED, THU, FRI]
ALLDAYS = [MON, TUE, WED, THU, FRI, SAT, SUN]


def sql_str(v) -> str:
    if v is None:
        return "null"
    if isinstance(v, bool):
        return "true" if v else "false"
    if isinstance(v, (int, float)):
        return str(v)
    if isinstance(v, date):
        return f"'{v.isoformat()}'"
    return "'" + str(v).replace("'", "''") + "'"


def header(title: str, note: str = "") -> str:
    bar = "-- " + "=" * 69
    out = f"{bar}\n-- RotaSorter seed — {title}\n"
    if note:
        out += textwrap.indent(textwrap.fill(note, 68), "-- ") + "\n"
    out += "-- Synthetic data only. Generated by supabase/seed/generate_seed.py\n"
    out += f"{bar}\n\n"
    return out


# =====================================================================
# Reference data
# =====================================================================

SHIFTS = [
    # code,  name,   start,     end,       is_default, sort
    ("DAY",  "Day",  "08:30",   "17:00",   True,  0),
    ("LATE", "Late", "17:00",   "20:30",   False, 1),
]

BENCH_GROUPS = [
    "Urines", "Enteric", "Reading", "Sensitivities", "Processing",
    "Rapid & ID", "Containment", "Sterile Sites", "Molecular & Serology",
    "Reporting",
]

# name, group, default min, default max, required_level,
# requirement rows on the Day shift as (label, weekdays, min, max),
# and the document numbers attached to the competency.
#
# A bench with no row for a given day is not staffed that day. Weekend cover is
# a separate, smaller requirement rather than the weekday one repeated.
BENCHES = [
    ("Urines", "Urines", 2, 3, "competent",
     [("standard", WEEKDAYS, 2, 3), ("weekend", [SAT, SUN], 1, 2)],
     [93, 411, 412, 394]),
    ("Screening, Faeces and Tips Reading", "Enteric", 1, 3, "competent",
     [("standard", WEEKDAYS, 1, 3)],
     [204, 206, 395, 414]),
    ("Faeces Microscopy", "Enteric", 1, 2, "competent",
     [("standard", [MON, WED, FRI], 1, 2)],
     [235]),
    ("Wounds Reading", "Reading", 1, 2, "competent",
     [("standard", WEEKDAYS, 1, 2)],
     [396]),
    ("Urogenitals Reading", "Reading", 1, 2, "competent",
     [("standard", [TUE, THU], 1, 2)],
     [399]),
    ("ENT Reading", "Reading", 1, 2, "competent",
     [("standard", [TUE, THU], 1, 2)],
     [397]),
    ("CAT-3 Reading", "Reading", 1, 2, "competent",
     [("standard", [WED, FRI], 1, 2)],
     [398]),
    ("EUCAST Sensitivity Testing", "Sensitivities", 1, 2, "competent",
     [("standard", WEEKDAYS, 1, 2)],
     [274]),
    ("Processing Anaerobes", "Processing", 1, 2, "competent",
     [("standard", [MON, WED, FRI], 1, 2)],
     [205, 134]),
    ("Deep Wounds/ Tissues", "Processing", 1, 2, "competent",
     [("standard", WEEKDAYS, 1, 2)],
     [401, 402, 403, 404, 407, 105]),
    ("Trichomonas, Grams and Broths", "Processing", 1, 2, "competent",
     [("standard", [TUE, THU], 1, 2)],
     [241, 400, 111, 406]),
    ("Quick Tests", "Rapid & ID", 1, 2, "competent",
     [("standard", WEEKDAYS, 1, 2)],
     [132, 114, 112, 133, 98, 142, 438, 143]),
    ("MALDI", "Rapid & ID", 1, 2, "competent",
     [("standard", WEEKDAYS, 1, 2)],
     [233]),
    ("CAT-3", "Containment", 1, 2, "competent",
     [("standard", [MON, WED], 1, 2)],
     [145, 323, 409, 410, 426, 433]),
    ("Mycology", "Containment", 1, 2, "competent",
     [("standard", [THU], 1, 2)],
     [339]),
    ("CSF", "Sterile Sites", 1, 1, "competent",
     [("standard", WEEKDAYS, 1, 1)],
     [263, 265]),
    ("Blood Cultures", "Sterile Sites", 1, 2, "competent",
     [("standard", WEEKDAYS, 1, 2), ("weekend", [SAT, SUN], 1, 1)],
     [266, 267]),
    ("Molecular", "Molecular & Serology", 1, 2, "competent",
     [("standard", [WED], 1, 2)],
     [234]),
    ("Serology", "Molecular & Serology", 1, 2, "competent",
     [("standard", [THU], 1, 2)],
     [99, 135, 136]),
    ("Reporting Ref Lab Reports", "Reporting", 1, 1, "competent",
     [("standard", [WED], 1, 1)],
     [432]),
]

# Titles for the document numbers, so the hover text on the matrix reads like a
# real document register rather than a bare number.
DOC_TITLES = {
    93: "Urine culture: inoculation and plate reading",
    411: "Urine microscopy and white cell counts",
    412: "Urine antigen and dipstick screening",
    394: "Urine specimen acceptance and rejection criteria",
    204: "Faecal culture: primary plating",
    206: "Rectal and wound screening swabs",
    395: "Tips and line culture reading",
    414: "Carbapenemase and MRSA screening plates",
    396: "Superficial wound plate reading",
    399: "Urogenital plate reading and interpretation",
    397: "ENT and eye plate reading",
    398: "Containment level 3 culture reading",
    274: "EUCAST disc diffusion sensitivity testing",
    205: "Anaerobic culture set-up and incubation",
    134: "Anaerobic identification and gas pack handling",
    132: "Rapid antigen testing",
    114: "Latex agglutination tests",
    112: "Oxidase, catalase and coagulase",
    133: "Beta-lactamase detection",
    98: "Germ tube test",
    142: "Rapid urease testing",
    438: "Lateral flow toxin testing",
    143: "Indole and spot tests",
    235: "Faecal parasitology microscopy",
    233: "MALDI-TOF target preparation and identification",
    339: "Mycology culture, microscopy and identification",
    145: "Containment level 3 entry, exit and PPE",
    323: "Mycobacterial culture set-up",
    409: "Auramine and ZN staining",
    410: "Containment level 3 waste and spill handling",
    426: "Mycobacterial molecular line probe assay",
    433: "Containment level 3 safety cabinet operation",
    263: "CSF microscopy and cell counts",
    265: "CSF culture, antigen testing and reporting",
    266: "Blood culture bottle handling and loading",
    267: "Positive blood culture work-up and gram stain",
    401: "Tissue and deep wound homogenisation",
    402: "Deep wound culture set-up",
    403: "Sonication of prosthetic material",
    404: "Tissue culture reading and interpretation",
    407: "Bone and joint sample handling",
    105: "Sterile site specimen receipt",
    241: "Trichomonas wet preparation microscopy",
    400: "Gram film preparation and reporting",
    111: "Broth culture set-up and subculture",
    406: "Genital specimen processing",
    234: "Molecular assay set-up and extraction",
    99: "Serology sample preparation",
    135: "Syphilis and treponemal serology",
    136: "Serology analyser operation and QC",
    432: "Reference laboratory report interpretation and filing",
}

# =====================================================================
# Staff
# =====================================================================

# key, code, name, grade, fte, weekdays worked, started_on
STAFF = [
    ("ali", "SBMS-0041", "Alison Ferreira",   "senior_bms", 1.00, WEEKDAYS, date(2011, 4, 4)),
    ("rak", "SBMS-0058", "Rakesh Menon",      "senior_bms", 1.00, WEEKDAYS, date(2013, 9, 2)),
    ("cla", "SBMS-0063", "Claire Dunwoody",   "senior_bms", 1.00, WEEKDAYS, date(2014, 1, 13)),
    ("pri", "BMS-0112",  "Priya Raman",       "bms",        1.00, WEEKDAYS, date(2017, 6, 5)),
    ("tom", "BMS-0127",  "Tom Whitfield",     "bms",        1.00, WEEKDAYS, date(2018, 2, 19)),
    ("gra", "BMS-0134",  "Grace Okonkwo",     "bms",        1.00, WEEKDAYS, date(2018, 10, 1)),
    ("mar", "BMS-0141",  "Marcus Kell",       "bms",        1.00, WEEKDAYS, date(2019, 3, 25)),
    ("sar", "BMS-0155",  "Sarah Patel",       "bms",        1.00, WEEKDAYS, date(2019, 11, 4)),
    ("dan", "BMS-0168",  "Daniel Achebe",     "bms",        0.80, [MON, TUE, WED, THU], date(2020, 7, 6)),
    ("nad", "BMS-0173",  "Nadia Hussain",     "bms",        0.80, [TUE, WED, THU, FRI], date(2021, 1, 11)),
    ("owe", "BMS-0189",  "Owen Brackley",     "bms",        1.00, WEEKDAYS, date(2021, 9, 13)),
    ("luc", "BMS-0194",  "Lucy Tran",         "bms",        1.00, [WED, THU, FRI, SAT, SUN], date(2022, 4, 19)),
    ("ibr", "BMS-0201",  "Ibrahim Sesay",     "bms",        1.00, [WED, THU, FRI, SAT, SUN], date(2022, 8, 30)),
    ("daw", "AP-0303",   "Dawn Rutherford",   "ap",         1.00, WEEKDAYS, date(2015, 5, 18)),
    ("kyl", "AP-0311",   "Kyle Mbeki",        "ap",         0.60, [MON, TUE, WED], date(2020, 2, 3)),
    ("fio", "AP-0318",   "Fiona Castellano",  "ap",         1.00, [WED, THU, FRI, SAT, SUN], date(2021, 6, 14)),
    ("ree", "AP-0326",   "Reece Underhill",   "ap",         1.00, WEEKDAYS, date(2023, 1, 9)),
    ("han", "TRN-0402",  "Hannah Ng",         "trainee",    1.00, WEEKDAYS, date(2025, 9, 1)),
    ("jos", "TRN-0409",  "Josef Kaminski",    "trainee",    1.00, WEEKDAYS, date(2026, 1, 12)),
    ("ama", "TRN-0415",  "Amara Diallo",      "trainee",    1.00, WEEKDAYS, date(2026, 4, 20)),
]

STAFF_BY_KEY = {s[0]: s for s in STAFF}

# staff key, start, end, kind, note
ABSENCES = [
    ("pri", date(2026, 9, 14), date(2026, 9, 16), "annual_leave", "Booked April"),
    ("tom", date(2026, 9, 17), date(2026, 9, 18), "annual_leave", None),
    ("gra", date(2026, 9, 15), date(2026, 9, 15), "sick", "Called in 07:10"),
    # Outside the seeded week, so the Staff detail screen has some history and
    # the following week is visibly harder than this one.
    ("mar", date(2026, 9, 28), date(2026, 10, 2), "annual_leave", None),
    ("han", date(2026, 9, 23), date(2026, 9, 23), "study", "University day"),
    ("daw", date(2026, 9, 21), date(2026, 9, 25), "annual_leave", None),
    ("ibr", date(2026, 9, 7),  date(2026, 9, 11), "annual_leave", None),
    ("ree", date(2026, 8, 24), date(2026, 8, 28), "annual_leave", None),
]

# bench name -> {staff key: level}
# 'trainer' can supervise, 'competent' is signed off, 'trainee' is on the bench
# while working through the documents.
COMPETENCY: dict[str, dict[str, str]] = {
    "Urines": {
        "ali": "trainer", "rak": "trainer", "cla": "competent", "pri": "competent",
        "tom": "competent", "gra": "competent", "mar": "competent", "sar": "competent",
        "dan": "competent", "nad": "competent", "owe": "competent", "luc": "competent",
        "ibr": "competent", "daw": "competent", "kyl": "competent", "fio": "competent",
        "ree": "competent", "han": "trainee", "jos": "trainee", "ama": "trainee",
    },
    "Screening, Faeces and Tips Reading": {
        "ali": "trainer", "rak": "competent", "cla": "trainer", "pri": "competent",
        "tom": "competent", "gra": "competent", "mar": "competent", "sar": "competent",
        "dan": "competent", "nad": "competent", "owe": "competent", "luc": "competent",
        "ibr": "competent", "daw": "competent", "ree": "competent",
        "han": "trainee", "jos": "trainee",
    },
    "Faeces Microscopy": {
        "ali": "trainer", "rak": "competent", "pri": "competent", "gra": "competent",
        "dan": "competent", "daw": "trainer", "ree": "competent", "kyl": "competent",
        "ama": "trainee",
    },
    "Wounds Reading": {
        "ali": "trainer", "rak": "competent", "cla": "trainer", "pri": "competent",
        "tom": "competent", "gra": "competent", "mar": "competent", "sar": "competent",
        "dan": "competent", "nad": "competent", "owe": "competent", "luc": "competent",
        "ibr": "competent", "han": "trainee",
    },
    "Urogenitals Reading": {
        "ali": "trainer", "cla": "trainer", "tom": "competent", "gra": "competent",
        "sar": "competent", "nad": "competent", "owe": "competent", "han": "trainee",
    },
    "ENT Reading": {
        "ali": "trainer", "cla": "trainer", "tom": "competent", "gra": "competent",
        "mar": "competent", "nad": "competent", "owe": "competent", "han": "trainee",
    },
    "CAT-3 Reading": {
        "ali": "trainer", "rak": "trainer", "cla": "competent", "mar": "competent",
        "owe": "competent",
    },
    "EUCAST Sensitivity Testing": {
        "ali": "trainer", "rak": "trainer", "cla": "competent", "pri": "competent",
        "tom": "competent", "gra": "competent", "mar": "competent", "sar": "competent",
        "dan": "competent", "nad": "competent", "owe": "competent", "luc": "competent",
        "ibr": "competent", "ama": "trainee",
    },
    "Processing Anaerobes": {
        "ali": "trainer", "rak": "competent", "pri": "competent", "mar": "competent",
        "dan": "competent", "daw": "trainer", "kyl": "competent", "ree": "competent",
        "fio": "competent", "jos": "trainee",
    },
    "Deep Wounds/ Tissues": {
        "ali": "trainer", "rak": "competent", "cla": "competent", "pri": "competent",
        "mar": "competent", "sar": "competent", "owe": "competent", "dan": "competent",
        "luc": "competent", "daw": "competent", "ree": "competent", "ama": "trainee",
    },
    "Trichomonas, Grams and Broths": {
        "ali": "trainer", "cla": "competent", "pri": "competent", "gra": "competent",
        "sar": "competent", "dan": "competent", "nad": "competent", "daw": "competent",
        "ree": "competent", "ama": "trainee",
    },
    "Quick Tests": {
        "ali": "trainer", "rak": "competent", "cla": "competent", "pri": "competent",
        "tom": "competent", "gra": "competent", "mar": "competent", "sar": "competent",
        "dan": "competent", "nad": "competent", "owe": "competent", "luc": "competent",
        "ibr": "competent", "daw": "trainer", "kyl": "competent", "fio": "competent",
        "ree": "competent", "han": "trainee", "jos": "trainee", "ama": "trainee",
    },
    "MALDI": {
        "ali": "trainer", "rak": "competent", "cla": "competent", "tom": "competent",
        "gra": "competent", "mar": "competent", "sar": "competent", "nad": "competent",
        "owe": "competent", "daw": "competent", "ree": "competent", "luc": "competent",
        "ibr": "competent",
    },
    "CAT-3": {
        "ali": "trainer", "rak": "trainer", "cla": "competent", "mar": "competent",
        "owe": "competent", "gra": "competent", "ama": "trainee",
    },
    # Deliberately thin: one signed-off mycologist. The Benches screen flags it,
    # and it is the first thing that breaks when Rakesh books leave.
    "Mycology": {
        "rak": "trainer", "han": "trainee", "jos": "trainee",
    },
    "CSF": {
        "ali": "trainer", "rak": "trainer", "cla": "competent", "tom": "competent",
        "sar": "competent", "owe": "competent", "luc": "competent",
    },
    "Blood Cultures": {
        "ali": "trainer", "rak": "competent", "cla": "trainer", "pri": "competent",
        "tom": "competent", "gra": "competent", "mar": "competent", "sar": "competent",
        "owe": "competent", "luc": "competent", "ibr": "competent", "nad": "competent",
        "jos": "trainee",
    },
    "Molecular": {
        "rak": "trainer", "cla": "competent", "nad": "competent", "owe": "competent",
        "jos": "trainee",
    },
    "Serology": {
        "ali": "trainer", "cla": "competent", "tom": "competent", "nad": "competent",
        "sar": "competent",
    },
    # Also deliberately thin: one person can sign off reference lab reports.
    "Reporting Ref Lab Reports": {
        "cla": "trainer",
    },
}

# (staff key, bench name) -> expires_on. Everything else gets a routine
# three-year expiry from its assessment date.
EXPIRY_OVERRIDES = {
    # Expired: these two are ineligible until reassessed.
    ("kyl", "Faeces Microscopy"): date(2026, 7, 30),
    ("ree", "Deep Wounds/ Tissues"): date(2026, 8, 5),
    # Expiring inside 60 days: caution glyph on the matrix and the Staff table,
    # all still valid through the seeded week.
    ("daw", "Quick Tests"): date(2026, 9, 22),
    ("mar", "CAT-3"): date(2026, 9, 30),
    ("gra", "Wounds Reading"): date(2026, 10, 1),
    ("sar", "Urines"): date(2026, 10, 2),
    ("owe", "Molecular"): date(2026, 10, 10),
    ("nad", "ENT Reading"): date(2026, 10, 15),
}

TRAINERS_FOR_SIGNOFF = ["ali", "rak", "cla", "daw"]

# =====================================================================
# Rules
#
# conditions is the tree the Rule Builder edits. Subjects and operators match
# the table in the design spec, section 3.6.
# =====================================================================

def cond(subject, operator, values):
    return {"subject": subject, "operator": operator, "values": values}


def all_of(*children):
    return {"op": "all", "children": list(children)}


RULES = [
    {
        "name": "CAT-3 needs a trainer on the bench",
        "description": "Containment level 3 work is never done unsupervised.",
        "action": "requires_supervisor",
        "params": {"supervisor_level": "trainer"},
        "conditions": all_of(cond("bench", "is", ["CAT-3"])),
        "scope": "bench",
        "is_hard": True,
        "weight": 100,
        "status": "active",
        "plain_english": "Any day CAT-3 is staffed, at least one person on it must be a trainer.",
    },
    {
        "name": "Reference lab reports need a Senior BMS",
        "description": "Only a senior signs off reference laboratory report interpretation.",
        "action": "requires_at_least",
        "params": {"n": 1},
        "conditions": all_of(
            cond("bench", "is", ["Reporting Ref Lab Reports"]),
            cond("grade", "is", ["senior_bms"]),
        ),
        "scope": "bench",
        "is_hard": True,
        "weight": 100,
        "status": "active",
        "plain_english": "Reporting Ref Lab Reports must have at least 1 Senior BMS on it.",
    },
    {
        "name": "Keep Marcus Kell and Sarah Patel apart",
        "description": "Requested by both. Do not put them on the same bench.",
        "action": "not_together",
        "params": {},
        "conditions": all_of(cond("person", "is one of", ["BMS-0141", "BMS-0155"])),
        "scope": "staff",
        "is_hard": True,
        "weight": 100,
        "status": "active",
        "plain_english": "Marcus Kell and Sarah Patel are never on the same bench on the same day.",
    },
    {
        "name": "No trainees on CSF",
        "description": "CSF is urgent and low volume; training happens elsewhere.",
        "action": "cannot_be_assigned",
        "params": {},
        "conditions": all_of(
            cond("grade", "is", ["trainee"]),
            cond("bench", "is", ["CSF"]),
        ),
        "scope": "bench",
        "is_hard": True,
        "weight": 100,
        "status": "active",
        "plain_english": "Anyone at Trainee grade cannot be assigned to CSF.",
    },
    {
        "name": "Hannah Ng holds one bench all week",
        "description": "Training block. Continuity matters more than variety while she signs off.",
        "action": "same_bench_all_week",
        "params": {},
        "conditions": all_of(cond("person", "is", ["TRN-0402"])),
        "scope": "staff",
        "is_hard": False,
        "weight": 70,
        "status": "active",
        "plain_english": "Hannah Ng should stay on the same bench every day this week.",
    },
    {
        "name": "Cap Urines at three days a week",
        "description": "Urines is the heaviest bench. Spread it.",
        "action": "max_shifts_in_period",
        "params": {"n": 3},
        "conditions": all_of(cond("bench", "is", ["Urines"])),
        "scope": "bench",
        "is_hard": False,
        "weight": 40,
        "status": "active",
        "plain_english": "Nobody should be on Urines more than 3 days in the week.",
    },
    {
        "name": "At most one trainee on Urines",
        "description": "One trainee at a time so the signed-off staff can actually supervise.",
        "action": "requires_at_most",
        "params": {"n": 1},
        "conditions": all_of(
            cond("bench", "is", ["Urines"]),
            cond("grade", "is", ["trainee"]),
        ),
        "scope": "bench",
        "is_hard": False,
        "weight": 50,
        "status": "active",
        "plain_english": "Urines should have at most 1 person at Trainee grade on it.",
    },
    {
        # Paused on purpose. Activate it on the Rules screen to watch the week
        # go infeasible and see the explanation screen do its job.
        "name": "Blood Cultures needs three people",
        "description": "Paused. Turn this on to demonstrate the infeasibility explanation.",
        "action": "requires_at_least",
        "params": {"n": 3},
        "conditions": all_of(cond("bench", "is", ["Blood Cultures"])),
        "scope": "bench",
        "is_hard": True,
        "weight": 100,
        "status": "paused",
        "plain_english": "Blood Cultures must have at least 3 people on it.",
    },
]

# Leaving someone on the rota doing nothing has to cost more than putting them
# on a bench they were already on this week, or the solver buys variety by
# benching people, which is worse than the repetition it avoids.
SOLVER_SETTINGS = [
    ("weight_fairness_spread", 20, "Fairness",
     "Cost per repeat of the gap between the most and least repeated person.", 0),
    ("weight_rotation_repeat", 12, "Rotation",
     "Cost each time someone repeats a bench they were already on this week.", 1),
    ("weight_idle_staff", 40, "Idle staff",
     "Cost of leaving an available member of staff off the rota for a day.", 2),
    ("weight_trainee_placement", 25, "Trainee placement",
     "Extra cost of leaving a trainee off the rota, on top of the idle cost.", 3),
    ("weight_soft_breach_scale", 1, "Soft rule scale",
     "Multiplier applied to each soft rule's own weight.", 4),
    ("max_solve_seconds", 60, "Solve time limit",
     "Seconds the CP-SAT solver may spend before returning its best answer.", 5),
    ("random_seed", 20260914, "Random seed",
     "Fixed so the same inputs give the same rota.", 6),
]


# =====================================================================
# Emitters
# =====================================================================

def emit_reference() -> str:
    out = header(
        "010 reference data",
        "Shifts, bench groups, the 20 benches and the competency documents "
        "attached to each. Document numbers are the provisional register.",
    )
    out += "begin;\n\n"
    out += "-- Wipe operational data first so this file can be re-run.\n"
    out += textwrap.dedent("""\
        truncate table rule_breach, assignment, pin, rota_week, rota_run,
                       staff_document, competency, availability, absence,
                       bench_shift_requirement, competency_document,
                       rule, solver_setting, staff, bench, bench_group, shift
                 restart identity cascade;

        """)

    out += "-- Shifts ------------------------------------------------------------\n"
    out += "insert into shift (code, name, starts_at, ends_at, is_default, sort_order) values\n"
    rows = [
        f"  ({sql_str(c)}, {sql_str(n)}, {sql_str(s)}, {sql_str(e)}, {sql_str(d)}, {o})"
        for c, n, s, e, d, o in SHIFTS
    ]
    out += ",\n".join(rows) + ";\n\n"

    out += "-- Bench groups ------------------------------------------------------\n"
    out += "insert into bench_group (name, sort_order) values\n"
    rows = [f"  ({sql_str(g)}, {i})" for i, g in enumerate(BENCH_GROUPS)]
    out += ",\n".join(rows) + ";\n\n"

    out += "-- Benches -----------------------------------------------------------\n"
    out += textwrap.dedent("""\
        with data(name, group_name, min_staff, max_staff, required_level, sort_order) as (
          values
        """)
    rows = []
    for i, (name, grp, mn, mx, lvl, _reqs, _docs) in enumerate(BENCHES):
        rows.append(
            f"    ({sql_str(name)}, {sql_str(grp)}, {mn}, {mx}, {sql_str(lvl)}, {i})"
        )
    out += ",\n".join(rows) + "\n)\n"
    out += textwrap.dedent("""\
        insert into bench (name, group_id, min_staff, max_staff, required_level, sort_order)
        select d.name, g.id, d.min_staff, d.max_staff, d.required_level::competency_level, d.sort_order
        from data d
        join bench_group g on g.name = d.group_name;

        """)

    out += "-- Competency documents ----------------------------------------------\n"
    out += "with data(bench_name, doc_number, title, is_primary, sort_order) as (\n  values\n"
    rows = []
    for name, _grp, _mn, _mx, _lvl, _reqs, docs in BENCHES:
        for i, doc in enumerate(docs):
            rows.append(
                f"    ({sql_str(name)}, {sql_str(str(doc))}, "
                f"{sql_str(DOC_TITLES[doc])}, {sql_str(i == 0)}, {i})"
            )
    out += ",\n".join(rows) + "\n)\n"
    out += textwrap.dedent("""\
        insert into competency_document (bench_id, doc_number, title, is_primary, sort_order)
        select b.id, d.doc_number, d.title, d.is_primary, d.sort_order
        from data d
        join bench b on b.name = d.bench_name;

        """)

    out += "-- Which benches run on which days ------------------------------------\n"
    out += "-- The Day shift only. See docs/ASSUMPTIONS.md for the Late shift.\n"
    out += "with data(bench_name, label, weekdays, min_staff, max_staff) as (\n  values\n"
    rows = []
    for name, _g, _mn, _mx, _l, reqs, _docs in BENCHES:
        for label, days, mn, mx in reqs:
            arr = "'{" + ",".join(str(d) for d in days) + "}'::smallint[]"
            rows.append(f"    ({sql_str(name)}, {sql_str(label)}, {arr}, {mn}, {mx})")
    out += ",\n".join(rows) + "\n)\n"
    out += textwrap.dedent("""\
        insert into bench_shift_requirement (bench_id, shift_id, label, weekdays,
                                             min_staff, max_staff)
        select b.id, s.id, d.label, d.weekdays, d.min_staff, d.max_staff
        from data d
        join bench b on b.name = d.bench_name
        join shift s on s.code = 'DAY';

        """)
    out += "commit;\n"
    return out


def emit_staff() -> str:
    out = header(
        "020 staff, patterns and absences",
        "20 synthetic staff across four grades, with contracted patterns that "
        "leave 1-3 people of headroom on a weekday and three on a weekend.",
    )
    out += "begin;\n\n"

    out += "-- Staff --------------------------------------------------------------\n"
    out += ("insert into staff (staff_code, full_name, grade, fte, started_on, status) "
            "values\n")
    rows = []
    for _k, code, name, grade, fte, _days, started in STAFF:
        rows.append(
            f"  ({sql_str(code)}, {sql_str(name)}, {sql_str(grade)}, "
            f"{fte:.2f}, {sql_str(started)}, 'active')"
        )
    out += ",\n".join(rows) + ";\n\n"

    out += "-- Contracted patterns (Day shift) ------------------------------------\n"
    out += "-- weekday is ISO: 1 = Monday .. 7 = Sunday. A row exists only for the\n"
    out += "-- days a person is contracted to work.\n"
    out += "with data(staff_code, weekday) as (\n  values\n"
    rows = []
    for _k, code, _n, _g, _f, days, _s in STAFF:
        for d in days:
            rows.append(f"    ({sql_str(code)}, {d}::smallint)")
    out += ",\n".join(rows) + "\n)\n"
    out += textwrap.dedent("""\
        insert into availability (staff_id, weekday, shift_id, is_available)
        select s.id, d.weekday, sh.id, true
        from data d
        join staff s on s.staff_code = d.staff_code
        join shift sh on sh.code = 'DAY';

        """)

    out += "-- Absences -----------------------------------------------------------\n"
    out += "with data(staff_code, starts_on, ends_on, kind, notes) as (\n  values\n"
    rows = []
    for key, start, end, kind, note in ABSENCES:
        code = STAFF_BY_KEY[key][1]
        rows.append(
            f"    ({sql_str(code)}, {sql_str(start)}, {sql_str(end)}, "
            f"{sql_str(kind)}, {sql_str(note)})"
        )
    out += ",\n".join(rows) + "\n)\n"
    out += textwrap.dedent("""\
        insert into absence (staff_id, starts_on, ends_on, kind, notes)
        select s.id, d.starts_on, d.ends_on, d.kind::absence_kind, d.notes
        from data d
        join staff s on s.staff_code = d.staff_code;

        """)
    out += "commit;\n"
    return out


def assessment_dates(key: str, bench: str, level: str):
    """Pick a believable assessment date and expiry for one matrix cell."""
    started = STAFF_BY_KEY[key][6]

    if level == "trainee":
        # Training started somewhere in the last few months, no expiry yet.
        assessed = TODAY - timedelta(days=RNG.randint(20, 200))
        if assessed < started:
            assessed = started + timedelta(days=14)
        return assessed, None

    earliest = max(started + timedelta(days=60), TODAY - timedelta(days=912))
    latest = TODAY - timedelta(days=60)
    if earliest > latest:
        earliest = latest - timedelta(days=30)
    span = (latest - earliest).days
    assessed = earliest + timedelta(days=RNG.randint(0, max(span, 1)))

    override = EXPIRY_OVERRIDES.get((key, bench))
    expires = override if override else assessed + timedelta(days=1095)
    return assessed, expires


def emit_competencies() -> str:
    out = header(
        "030 competency matrix",
        "Who is signed off on what, at what level, and when it expires. The "
        "per-document evidence trail is derived from this.",
    )
    out += "begin;\n\n"

    out += "-- Bench-level competency (what the matrix screen edits) ---------------\n"
    out += ("with data(staff_code, bench_name, level, assessed_on, expires_on, "
            "assessor_code) as (\n  values\n")
    rows = []
    trainee_cells = []
    for bench_name, holders in COMPETENCY.items():
        for key, level in holders.items():
            code = STAFF_BY_KEY[key][1]
            assessed, expires = assessment_dates(key, bench_name, level)
            if level == "trainee":
                assessor = None
                trainee_cells.append((key, bench_name, assessed))
            else:
                pool = [t for t in TRAINERS_FOR_SIGNOFF if t != key]
                assessor = STAFF_BY_KEY[RNG.choice(pool)][1]
            rows.append(
                f"    ({sql_str(code)}, {sql_str(bench_name)}, {sql_str(level)}, "
                f"{sql_str(assessed)}, {sql_str(expires)}, {sql_str(assessor)})"
            )
    out += ",\n".join(rows) + "\n)\n"
    out += textwrap.dedent("""\
        insert into competency (staff_id, bench_id, level, assessed_on, expires_on,
                                assessor_id, document_ref)
        select
          s.id,
          b.id,
          d.level::competency_level,
          d.assessed_on::date,
          d.expires_on::date,
          a.id,
          (select cd.doc_number
             from competency_document cd
            where cd.bench_id = b.id
            order by cd.sort_order
            limit 1)
        from data d
        join staff s on s.staff_code = d.staff_code
        join bench b on b.name = d.bench_name
        left join staff a on a.staff_code = d.assessor_code;

        """)

    out += "-- Evidence trail: signed-off staff hold every document for the bench --\n"
    out += textwrap.dedent("""\
        insert into staff_document (staff_id, document_id, status, assessed_on, expires_on)
        select c.staff_id, cd.id, 'signed_off', c.assessed_on, c.expires_on
        from competency c
        join competency_document cd on cd.bench_id = c.bench_id
        where c.level in ('competent', 'trainer')
        on conflict (staff_id, document_id) do nothing;

        """)

    out += "-- Trainees are partway through, document by document ------------------\n"
    out += "with data(staff_code, bench_name, doc_number, status, assessed_on) as (\n  values\n"
    rows = []
    for key, bench_name, assessed in trainee_cells:
        code = STAFF_BY_KEY[key][1]
        docs = next(d for b, _g, _mn, _mx, _l, _r, d in BENCHES if b == bench_name)
        # Roughly the first half signed off, the rest live or not yet started.
        done = RNG.randint(0, max(len(docs) - 1, 0))
        for i, doc in enumerate(docs):
            if i < done:
                status = "signed_off"
                when = assessed + timedelta(days=i * 9)
            elif i == done:
                status = "in_training"
                when = None
            else:
                status = "not_started"
                when = None
            rows.append(
                f"    ({sql_str(code)}, {sql_str(bench_name)}, {sql_str(str(doc))}, "
                f"{sql_str(status)}, {sql_str(when)})"
            )
    out += ",\n".join(rows) + "\n)\n"
    out += textwrap.dedent("""\
        insert into staff_document (staff_id, document_id, status, assessed_on)
        select s.id, cd.id, d.status::doc_status, d.assessed_on::date
        from data d
        join staff s on s.staff_code = d.staff_code
        join bench b on b.name = d.bench_name
        join competency_document cd on cd.bench_id = b.id and cd.doc_number = d.doc_number
        on conflict (staff_id, document_id) do nothing;

        """)
    out += "commit;\n"
    return out


def emit_rules() -> str:
    import json

    out = header(
        "040 rules and solver settings",
        "Seven active rules plus one paused rule you can switch on to see the "
        "infeasibility explanation do its job.",
    )
    out += "begin;\n\n"

    out += "-- Rules --------------------------------------------------------------\n"
    out += "-- Condition values reference staff by staff_code and benches by name;\n"
    out += "-- the solver resolves them at load time.\n"
    out += ("insert into rule (name, description, action, params, conditions, scope, "
            "is_hard, weight, status, plain_english) values\n")
    rows = []
    for r in RULES:
        rows.append(
            "  (\n"
            f"    {sql_str(r['name'])},\n"
            f"    {sql_str(r['description'])},\n"
            f"    {sql_str(r['action'])},\n"
            f"    {sql_str(json.dumps(r['params']))}::jsonb,\n"
            f"    {sql_str(json.dumps(r['conditions']))}::jsonb,\n"
            f"    {sql_str(r['scope'])},\n"
            f"    {sql_str(r['is_hard'])},\n"
            f"    {r['weight']},\n"
            f"    {sql_str(r['status'])},\n"
            f"    {sql_str(r['plain_english'])}\n"
            "  )"
        )
    out += ",\n".join(rows) + ";\n\n"

    out += "-- Solver settings ----------------------------------------------------\n"
    out += "insert into solver_setting (key, value, label, description, sort_order) values\n"
    rows = [
        f"  ({sql_str(k)}, {sql_str(str(v))}::jsonb, {sql_str(label)}, {sql_str(desc)}, {order})"
        for k, v, label, desc, order in SOLVER_SETTINGS
    ]
    out += ",\n".join(rows) + ";\n\n"
    out += "commit;\n"
    return out


def main() -> None:
    files = {
        "0010_reference_data.sql": emit_reference(),
        "0020_staff.sql": emit_staff(),
        "0030_competencies.sql": emit_competencies(),
        "0040_rules_settings.sql": emit_rules(),
    }
    for name, body in files.items():
        (OUT / name).write_text(body)
        print(f"wrote {name} ({len(body.splitlines())} lines)")

    # A quick arithmetic sanity check on the week, printed so a change to the
    # roster or the bench list shows up as a warning rather than a failed solve.
    print("\nweekday headroom for the seeded week:")
    for offset, label in enumerate(["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]):
        day = SEED_WEEK + timedelta(days=offset)
        iso = offset + 1
        available = 0
        for key, _c, _n, _g, _f, days, _s in STAFF:
            if iso not in days:
                continue
            if any(k == key and s <= day <= e for k, s, e, _kind, _note in ABSENCES):
                continue
            available += 1
        needed = sum(
            mn
            for _n, _g, _dmn, _dmx, _l, reqs, _d in BENCHES
            for _label, days, mn, _mx in reqs
            if iso in days
        )
        # A trainee placed on a bench that needs one person consumes two: the
        # trainee and the colleague supervising them. Two spare is the floor
        # that keeps three trainees placeable.
        flag = "  <-- TIGHT" if available - needed < 2 else ""
        print(f"  {label}: {needed} needed, {available} available, "
              f"headroom {available - needed}{flag}")


if __name__ == "__main__":
    main()
