/**
 * The TypeScript solver must agree with the Python reference solver.
 *
 * Both are exact optimisers, so equal optimal objective values is a strong
 * statement that the two models are the same model — a mis-ported constraint or
 * a wrong objective weight moves the optimum. The fixtures are generated by
 * `python -m rotasolver.export_fixture`; regenerate them when the model changes.
 */

import { readFileSync } from "node:fs";
import { fileURLToPath } from "node:url";
import { dirname, join } from "node:path";
import { describe, expect, it } from "vitest";
import { solveWeek } from "./solve";
import { buildModel } from "./build";
import { ProblemIndex } from "./problem";
import { groupKey, type SolverProblem } from "./types";

const HERE = dirname(fileURLToPath(import.meta.url));
const FIXTURES = join(HERE, "__fixtures__");

interface Expected {
  status: string;
  objectiveValue: number | null;
  assignments: { workDate: string; benchId: string; staffId: string }[];
  breaches: { ruleName: string; detail: string }[];
  infeasibleConflictKinds: string[];
  infeasibleBenchNames: string[];
}

const manifest: string[] = JSON.parse(
  readFileSync(join(FIXTURES, "manifest.json"), "utf8"),
);

function load(name: string): { problem: SolverProblem; expected: Expected } {
  return JSON.parse(readFileSync(join(FIXTURES, `${name}.json`), "utf8"));
}

// Each case is solved once and every assertion reads the same answer. Solving
// per assertion instead turned a two second suite into a twenty five second one.
const solved = new Map<string, ReturnType<typeof solveWeek>>();
function solveOnce(name: string, problem: SolverProblem) {
  let pending = solved.get(name);
  if (!pending) {
    pending = solveWeek(problem);
    solved.set(name, pending);
  }
  return pending;
}

describe.each(manifest)("case: %s", (name) => {
  const { problem, expected } = load(name);

  it("reaches the same verdict as the reference solver", async () => {
    const result = await solveOnce(name, problem);
    expect(result.status, result.log).toBe(expected.status);
  });

  if (["solved", "solved_with_breaches"].includes(load(name).expected.status)) {
    it("finds an equally good rota", async () => {
      const result = await solveOnce(name, problem);
      // Equal optima, not identical rotas: with ties the two solvers may pick
      // different assignments of the same cost, which is fine.
      expect(result.objectiveValue).toBe(expected.objectiveValue);
    });

    it("places the same number of people", async () => {
      const result = await solveOnce(name, problem);
      expect(result.assignments.length).toBe(expected.assignments.length);
    });

    it("breaches the same soft rules", async () => {
      const result = await solveOnce(name, problem);
      expect(result.breaches.map((b) => b.ruleName).sort()).toEqual(
        expected.breaches.map((b) => b.ruleName).sort(),
      );
    });

    it("meets every coverage minimum and maximum", async () => {
      const result = await solveOnce(name, problem);
      const index = new ProblemIndex(problem);
      const placed = new Map<string, number>();
      for (const a of result.assignments) {
        const key = groupKey(a.workDate, a.shiftId, a.benchId);
        placed.set(key, (placed.get(key) ?? 0) + 1);
      }
      for (const date of index.dates) {
        for (const req of index.requirementsOn(date)) {
          const got = placed.get(groupKey(date, req.shiftId, req.benchId)) ?? 0;
          const bench = index.bench(req.benchId).name;
          expect(got, `${bench} on ${date} has ${got}, needs ${req.minStaff}`)
            .toBeGreaterThanOrEqual(req.minStaff);
          if (req.maxStaff != null) {
            expect(got, `${bench} on ${date} has ${got}, max ${req.maxStaff}`)
              .toBeLessThanOrEqual(req.maxStaff);
          }
        }
      }
    });

    it("honours every pin", async () => {
      const result = await solveOnce(name, problem);
      for (const pin of problem.pins) {
        const found = result.assignments.some(
          (a) =>
            a.staffId === pin.staffId &&
            a.benchId === pin.benchId &&
            a.workDate === pin.workDate,
        );
        expect(found, `pin for ${pin.staffId} on ${pin.benchId}`).toBe(true);
      }
    });

    it("never leaves a trainee unsupervised", async () => {
      const result = await solveOnce(name, problem);
      const index = new ProblemIndex(problem);
      const grouped = new Map<string, string[]>();
      for (const a of result.assignments) {
        const key = `${a.workDate}|${a.benchId}`;
        grouped.set(key, [...(grouped.get(key) ?? []), a.staffId]);
      }
      for (const [key, staffIds] of grouped) {
        const [date, benchId] = key.split("|");
        const trainees = staffIds.filter((s) => !index.isSignedOff(s, benchId, date));
        if (!trainees.length) continue;
        const supervisors = staffIds.filter((s) => index.isSignedOff(s, benchId, date));
        expect(
          supervisors.length,
          `${trainees.map((s) => index.staff(s).fullName)} alone on ` +
            `${index.bench(benchId).name} on ${date}`,
        ).toBeGreaterThan(0);
      }
    });
  } else {
    it("names the same kind of conflict", async () => {
      const result = await solveOnce(name, problem);
      const kinds = [
        ...new Set((result.infeasibleReport?.conflicts ?? []).map((c) => c.kind)),
      ].sort();
      expect(kinds).toEqual(expected.infeasibleConflictKinds);
    });

    it("names the same bench", async () => {
      const result = await solveOnce(name, problem);
      const names = [
        ...new Set(
          (result.infeasibleReport?.conflicts ?? [])
            .map((c) => c.bench_name)
            .filter(Boolean),
        ),
      ].sort();
      expect(names).toEqual(expected.infeasibleBenchNames);
    });

    it("offers a way out", async () => {
      const result = await solveOnce(name, problem);
      expect(result.infeasibleReport?.suggestions.length).toBeGreaterThan(0);
    });
  }
});

describe("model shape", () => {
  it("is a pure MIP of the size the reference solver reported", () => {
    const { problem } = load("seeded-week");
    const built = buildModel(problem);
    expect(built.slots.length).toBeGreaterThan(600);
    expect(built.model.binaryCount).toBeGreaterThan(600);
    expect(built.model.trivallyInfeasible).toBeNull();
  });
});
